package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Klient.java
//  @ Date : 15.06.2025
//  @ Author : 
//
//


import java.util.List;

public class Klient {
    private String imie;
    private List<Produkt> koszyk;

    public Klient(String imie, List<Produkt> koszyk) {
        this.imie = imie;
        this.koszyk = koszyk;
    }

    public void sprawdzRabaty() {
        Odwiedzajacy wizytor = new Odwiedzajacy();
        for (Produkt produkt : koszyk) {
            produkt.accept(wizytor);
        }
        System.out.println("Suma rabatów dla klienta " + imie + ": " + wizytor.getSumaRabatu());
    }
}
