package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Laptop.java
//  @ Date : 15.06.2025
//  @ Author : 
//
//

public class Laptop implements Produkt {
	public float cena;

	public Laptop(float cena) {
		this.cena = cena;
	}

	public float getCena() {
		return cena;
	}

	public void accept(Wizytator w) {
		w.zobaczLaptop(this);
	}
}
