package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Odwiedzajacy.java
//  @ Date : 15.06.2025
//  @ Author : 
//
//

public class Odwiedzajacy implements Wizytator {
	private float sumaRabatu = 0;

	public void zobaczLaptop(Laptop laptop) {
		float rabat = laptop.getCena() * 0.10f;
		sumaRabatu += rabat;
		System.out.println("Rabat na laptop: " + rabat);
	}

	public void zobaczTelefon(Telefon telefon) {
		float rabat = telefon.getCena() * 0.05f;
		sumaRabatu += rabat;
		System.out.println("Rabat na telefon: " + rabat);
	}

	public void zobaczTablet(Tablet tablet) {
		float rabat = tablet.getCena() * 0.02f;
		sumaRabatu += rabat;
		System.out.println("Rabat na tablet: " + rabat);
	}

	public float getSumaRabatu() {
		return sumaRabatu;
	}
}
