package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Produkt.java
//  @ Date : 15.06.2025
//  @ Author : 
//
//

public interface Produkt {
	float getCena();
	public void accept(Wizytator w);
}
