package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tablet.java
//  @ Date : 15.06.2025
//  @ Author : 
//
//

public class Tablet implements Produkt {
	private float cena;

	public Tablet(float cena) {
		this.cena = cena;
	}

	public float getCena() {
		return cena;
	}

	public void accept(Wizytator w) {
		w.zobaczTablet(this);
	}
}
