package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Telefon.java
//  @ Date : 15.06.2025
//  @ Author : 
//
//

public class Telefon implements Produkt {
	public float cena;

	public Telefon(float cena) {
		this.cena = cena;
	}

	public float getCena() {
		return cena;
	}

	public void accept(Wizytator w) {
		w.zobaczTelefon(this);
	}
}
