package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Wizytor.java
//  @ Date : 15.06.2025
//  @ Author : 
//
//

public interface Wizytator {
	void zobaczLaptop(Laptop laptop);
	void zobaczTelefon(Telefon telefon);
	void zobaczTablet(Tablet tablet);
}
