//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Klient.java
//  @ Date : 23.05.2025
//  @ Author : 
//
//
package org.example;


public class Klient implements Newsletter{
	public String Imie;

	public Klient(String Imie) {
		this.Imie = Imie;
	}

	@Override
	public void powiadom(String oferta) {
		System.out.println("Nowa oferta dla " + Imie + ": " +  oferta);
	}
}
