//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : KlientbezSubskrypcji.java
//  @ Date : 23.05.2025
//  @ Author : 
//
//
package org.example;


public class KlientbezSubskrypcji implements Newsletter {

	@Override
	public void powiadom(String oferta) {
		System.out.println("Ignorowanie ofert");
	}
}
