//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Newsletter.java
//  @ Date : 23.05.2025
//  @ Author : 
//
//
package org.example;

public interface Newsletter {
	void powiadom(String oferta);
}
