//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Oferta.java
//  @ Date : 23.05.2025
//  @ Author : 
//
//
package org.example;

public class Oferta {
    private String opis;

    public Oferta(String opis) {
        this.opis = opis;
    }
    public String getOpis() {
        return opis;
    }
}
