package org.example;

import java.util.ArrayList;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OperatorSieciKom�kowej.java
//  @ Date : 23.05.2025
//  @ Author : 
//
//
public class OperatorSieciKomokowej {
    public List<Newsletter> subskrybenci = new ArrayList<>();

	public void zarejestruj(Newsletter subskrybent) {
		subskrybenci.add(subskrybent);
	}

	public void wyrejestruj(Newsletter subskrybent) {
		subskrybenci.remove(subskrybent);
	}

	public void nowaOferata(String oferta) {
		System.out.println("Nowa oferta: " + oferta);
		for( Newsletter subskrybent : subskrybenci ) {
			subskrybent.powiadom(oferta);
		}

	}
}
