package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bank.java
//  @ Date : 03.06.2025
//  @ Author : 
//
//

public class Bank {
	private Konto konto;
	private HistoriaCommand historia;

	public Bank(Konto konto, HistoriaCommand historia) {
		this.konto = konto;
		this.historia = new HistoriaCommand();
	}

	public void wykonaj(Command command) {
		command.wykonaj();
		historia.dodaj(command);
	}

	public void cofnij() {
		Command ostatnia = historia.pobierz();
		if (ostatnia != null) {
			ostatnia.cofnij();
		}
	}
}
