package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CofnijCommand.java
//  @ Date : 03.06.2025
//  @ Author : 
//
//

public class CofnijCommand extends Command {
	private Bank bank;

	public CofnijCommand(Bank bank) {
		super(null, 0);
		this.bank = bank;
	}

	@Override
	public void wykonaj() {
		bank.cofnij();
	}

	@Override
	public void cofnij() {}
}
