package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Command.java
//  @ Date : 03.06.2025
//  @ Author : 
//
//

public abstract class Command {
	public Konto konto;
	public float kwota ;

	public Command(Konto konto, float kwota) {
		this.konto = konto;
		this.kwota = kwota;
	}

	public void zapiszKopie() {
		konto.zapiszStan();
	}
	
	public abstract void wykonaj();
	
	public abstract void cofnij();
}
