package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HistoriaCommand.java
//  @ Date : 03.06.2025
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.List;

public class HistoriaCommand {
	private List<Command> historia = new ArrayList<>();

	public void dodaj(Command command) {
		historia.add(command);
	}

	public Command pobierz() {
		if (historia.isEmpty()) return null;
		return historia.remove(historia.size() - 1);
	}
}
