package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Konto.java
//  @ Date : 03.06.2025
//  @ Author : 
//
//

public class Konto {
	public float saldo;
	private float poprzednieSaldo;

	public void wplata(float kwota) {
		saldo += kwota;
	}

	public void wyplata(float kwota) {
		saldo -= kwota;
	}

	public void zapiszStan() {
		poprzednieSaldo = saldo;
	}

	public void przywrocStan() {
		saldo = poprzednieSaldo;
	}

	public float getSaldo() {
		return saldo;
	}
}
