package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PrzelewCommand.java
//  @ Date : 03.06.2025
//  @ Author : 
//
//


public class PrzelewCommand extends Command {

	private Konto kontoDocelowe;

	public PrzelewCommand(Konto kontoZrodlowe, Konto kontoDocelowe, float kwota) {
		super(kontoZrodlowe, kwota);
		this.kontoDocelowe = kontoDocelowe;
	}

	@Override
	public void wykonaj() {
		zapiszKopie();
		konto.wyplata(kwota);
		kontoDocelowe.wplata(kwota);
	}

	@Override
	public void cofnij() {
		konto.przywrocStan();
		kontoDocelowe.wyplata(kwota);
	}
}
