package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Przycisk.java
//  @ Date : 03.06.2025
//  @ Author : 
//
//


public class Przycisk {
    private Command command;

    public Przycisk(Command command) {
        this.command = command;
    }

    public void kliknij() {
        command.wykonaj();
    }
}
