package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WyplataCommand.java
//  @ Date : 03.06.2025
//  @ Author : 
//
//

public class WyplataCommand extends Command {

	public WyplataCommand(Konto konto, float kwota) {
		super(konto, kwota);
	}

	@Override
	public void wykonaj() {
		zapiszKopie();
		konto.wyplata(kwota);
	}

	@Override
	public void cofnij() {
		konto.przywrocStan();
	}
}
