package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BudowniczyTort.java
//  @ Date : 06.06.2025
//  @ Author : 
//
//

public class BudowniczyTort implements TworcaTortu {
	private Tort tort;

	public void usun() {
		tort = new Tort();
	}

	public void dodajWarstwy() {
		tort.setWarstwy("warstwa biszkoptowa");
	}

	public void dodajNadzienie() {
		tort.setNadzienie("krem waniliowy");
	}

	public void dodajPolewe() {
		tort.setPolewa("polewa czekoladowa");
	}

	public void dodajOzdoby() {
		tort.setOzdoby("owoce, figurki");
	}

	public Tort wynik() {
		return tort;
	}
}
