package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BudowniczyInstrukcjaTort.java
//  @ Date : 06.06.2025
//  @ Author : 
//
//

public class BudowniczyInstrukcjaTort implements TworcaTortu {
	private Instrukcja instrukcja;

	public void usun() {
		instrukcja = new Instrukcja();
	}

	public void dodajWarstwy() {
		instrukcja.dodaj("Ułóż warstwe biszkoptu.");
	}

	public void dodajNadzienie() {
		instrukcja.dodaj("Nałóż krem waniliowy między warstwami.");
	}

	public void dodajPolewe() {
		instrukcja.dodaj("Oblej tort polewą czekoladową.");
	}

	public void dodajOzdoby() {
		instrukcja.dodaj("Udekoruj tort owocami i dodaj figurki.");
	}

	public Instrukcja wynik() {
		return instrukcja;
	}
}
