package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cukiernik.java
//  @ Date : 06.06.2025
//  @ Author : 
//
//

public class Cukiernik {
	public void zrobTortUrodzinowy(TworcaTortu budowniczy) {
		budowniczy.usun();
		budowniczy.dodajWarstwy();
		budowniczy.dodajNadzienie();
		budowniczy.dodajPolewe();
		budowniczy.dodajOzdoby();
	}

	public void zrobTortWeselny(TworcaTortu budowniczy) {
		budowniczy.usun();
		budowniczy.dodajWarstwy();
		budowniczy.dodajNadzienie();
		budowniczy.dodajWarstwy();
		budowniczy.dodajNadzienie();
		budowniczy.dodajWarstwy();
		budowniczy.dodajPolewe();
	}
}
