package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Instrukcja.java
//  @ Date : 06.06.2025
//  @ Author : 
//
//

public class Instrukcja {
    private StringBuilder instrukcje = new StringBuilder();

    public void dodaj(String krok) {
        instrukcje.append(krok).append("\n");
    }

    @Override
    public String toString() {
        return "Instrukcja przygotowania tortu:\n" + instrukcje.toString();
    }
}
