package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tort.java
//  @ Date : 06.06.2025
//  @ Author : 
//
//

public class Tort {
    private String warstwy = "";
    private String nadzienie = "";
    private String polewa = "";
    private String ozdoby = "";

    public void setWarstwy(String w) { this.warstwy = w; }
    public void setNadzienie(String n) { this.nadzienie = n; }
    public void setPolewa(String p) { this.polewa = p; }
    public void setOzdoby(String o) { this.ozdoby = o; }

    @Override
    public String toString() {
        return "Tort: " + warstwy + ", " + nadzienie + ", " + polewa + ", " + ozdoby;
    }
}
