package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TworcaTortu.java
//  @ Date : 06.06.2025
//  @ Author : 
//
//

public interface TworcaTortu {
	void usun();
	void dodajWarstwy();
	void dodajNadzienie();
	void dodajPolewe();
	void dodajOzdoby();
}
