package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : KoszykZakupow.java
//  @ Date : 04.06.2025
//  @ Author : 
//
//

public interface KoszykZakupow {
	Memento zapisz();
}
