package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : KoszykUzytkownika.java
//  @ Date : 04.06.2025
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.List;

public class KoszykUzytkownika implements KoszykZakupow {
	public List<String> produkty = new ArrayList<>();

	public void dodajProdukt(String produkt) {
		produkty.add(produkt);
	}

	public void usunProdukt(String produkt) {
		produkty.remove(produkt);
	}

	public void wyswietlProdukty() {
		System.out.println("Produkty w koszyku: " + produkty);
	}

	@Override
	public Memento zapisz() {
		return new KoszykMemento(this, new ArrayList<>(produkty));
	}

	public void ustawStan(List<String> stan) {
		produkty = new ArrayList<>(stan);
	}
}
