package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : KoszykMemento.java
//  @ Date : 04.06.2025
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.List;

public class KoszykMemento implements Memento {
	private KoszykUzytkownika koszyk;
	private List<String> stan;

	public KoszykMemento(KoszykUzytkownika koszyk, List<String> stan) {
		this.koszyk = koszyk;
		this.stan = stan;
	}

	@Override
	public void przywroc() {
		koszyk.ustawStan(stan);
	}
}
