package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Memento.java
//  @ Date : 04.06.2025
//  @ Author : 
//
//

public interface Memento {
	public void przywroc();
}
