package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Uytkownik.java
//  @ Date : 04.06.2025
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.List;

public class Uytkownik {
	private final List<Memento> historia = new ArrayList<>();

	public void zapiszStanKoszyka(Memento memento) {
		historia.add(memento);
	}

	public void cofnij() {
		if (!historia.isEmpty()) {
			Memento ostatni = historia.remove(historia.size() - 1);
			ostatni.przywroc();
		} else {
			System.out.println("Brak zapisanych stanów do przywrócenia.");
		}
	}
}
