package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MinimalnaLiczbaDni.java
//  @ Date : 07.06.2025
//  @ Author : 
//
//

public class MinimalnaLiczbaDni implements Wyrazenie {
	private Rezerwacja kontekst;
	private int min;

	public MinimalnaLiczbaDni(Rezerwacja kontekst, int min) {
		this.kontekst = kontekst;
		this.min = min;
	}

	@Override
	public boolean interpretuj() {
		return kontekst.liczbaNocy >= min;
	}

	@Override
	public String toString() {
		return "Warunek: czy liczba nocy >= " + min + "?";
	}
}
