package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Wyrazenie.java
//  @ Date : 07.06.2025
//  @ Author : 
//
//

public interface Wyrazenie {
	boolean interpretuj();
}
