package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WyrazenieI.java
//  @ Date : 07.06.2025
//  @ Author : 
//
//


public class WyrazenieI implements Wyrazenie {
	private Wyrazenie lewe;
	private Wyrazenie prawe;

	public WyrazenieI(Wyrazenie lewe, Wyrazenie prawe) {
		this.lewe = lewe;
		this.prawe = prawe;
	}

	@Override
	public boolean interpretuj() {
		return lewe.interpretuj() && prawe.interpretuj();
	}

	@Override
	public String toString() {
		return "(" + lewe.toString() + " I " + prawe.toString() + ")";
	}
}
