package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Edytor.java
//  @ Date : 13.06.2025
//  @ Author : 
//
//


public abstract class Edytor {
	public FormatDokumentu format;

	public Edytor(FormatDokumentu format) {
		this.format = format;
	}

	public void wpisz(String tekst) {
		System.out.println("Wpisano tekst: " + tekst);
	}
	
	public void zapisz(String tresc) {
		System.out.println("Zapisano.");
		format.zapisz(tresc);
	}
	
	public void cofnij() {
		System.out.println("Cofnieto ostatnie zmiany");
	}
	
	public void podglad() {
		System.out.println("Podglad.");
	}
}
