package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FormatDokumentu.java
//  @ Date : 13.06.2025
//  @ Author : 
//
//

public interface FormatDokumentu {
	public void zapisz(String tekst);
	
	public void dodajNaglowek(String tekst);
	
	public void dodajStopke(String tekst);
}
