package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PDF.java
//  @ Date : 13.06.2025
//  @ Author : 
//
//

public class PDF implements FormatDokumentu {

	@Override
	public void zapisz(String tekst) {
		System.out.println("Zapisano do PDF: " + tekst);
	}

	@Override
	public void dodajNaglowek(String tekst) {
		System.out.println("Dodano naglowek: " + tekst);
	}

	@Override
	public void dodajStopke(String tekst) {
		System.out.println("Dodano stopke:" + tekst);
	}
}
