package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProsteEdytowanie.java
//  @ Date : 13.06.2025
//  @ Author : 
//
//

public class ProsteEdytowanie extends Edytor {

	public ProsteEdytowanie(FormatDokumentu format) {
		super(format);
	}

	public void zwiekszCzcionke() {
		System.out.println("Zwiekszono czcionke");
	}
	
	public void dodajNaglowek(String tekst) {
		System.out.println("dodano naglowek");
		format.dodajNaglowek(tekst);
	}
}
