package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ZaawansowaneEdytowanie.java
//  @ Date : 13.06.2025
//  @ Author : 
//
//

public class ZaawansowaneEdytowanie extends Edytor {

	public ZaawansowaneEdytowanie(FormatDokumentu format) {
		super(format);
	}

	public void zmienRodzajCzcionki(String czcionka) {
		System.out.println("Zmieniono czcionkę: " + czcionka);
	}

	public void dodajStopkeINaglowek(String naglowek, String stopka) {
		format.dodajNaglowek(naglowek);
		format.dodajStopke(stopka);
	}

	public void szyfrujZapis(String tresc) {
		System.out.println("Zaszyfrowano zawartość...");
		format.zapisz("zaszyfrowany tekst");
	}
}
