#include <iostream>

using namespace std;

//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AktualizacjaSystemu.cpp
//  @ Date : 24.05.2025
//  @ Author :
//
//

class AktualizacjaSystemu {
private:
    static AktualizacjaSystemu*  instance;
    void AktualizacjaSustemu();
    string aktualizacja = "Brak aktualizacji";

public:
    static AktualizacjaSystemu* getInstance(){
        if(instance == nullptr){
            instance = new AktualizacjaSystemu();
        }
        return instance;
    }

    void pobierzAktualizacje(){
        aktualizacja = "Aktualizacja systemu - najnowsza wersja. ";
        std::cout<< "Pobrano : " << aktualizacja <<endl;
    }

    void sprawdzAktualizacje(){
        cout<<"Sprawdzanie aktualizacji...  "<< aktualizacja << endl;
    }

};

AktualizacjaSystemu* AktualizacjaSystemu::instance = nullptr;

int main()
{
    AktualizacjaSystemu* system = AktualizacjaSystemu::getInstance();
    AktualizacjaSystemu* system2 = AktualizacjaSystemu::getInstance();
    system->sprawdzAktualizacje();
    system->pobierzAktualizacje();
    system->sprawdzAktualizacje();
    system2->sprawdzAktualizacje();

    return 0;
}
