package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Dzwiek.java
//  @ Date : 31.05.2025
//  @ Author : 
//
//

public interface Dzwiek {
	 void start();
	 void stop();
}
