package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Playlista.java
//  @ Date : 31.05.2025
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.List;

public class Playlista implements Dzwiek {
	private String nazwa;
	private List<Dzwiek> elementy = new ArrayList<>();

	public Playlista(String nazwa) {
		this.nazwa = nazwa;
	}

	public void dodaj(Dzwiek dzwiek) {
		elementy.add(dzwiek);
	}

	public void start() {
		System.out.println("Odtwarzam playliste: " + nazwa);
		for (Dzwiek element : elementy) {
			element.start();
		}
	}
	
	public void stop() {
		System.out.println("Zatrzymano playliste: " + nazwa);
		for (Dzwiek element : elementy) {
			element.stop();
		}
	}
}
