package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Utwor.java
//  @ Date : 31.05.2025
//  @ Author : 
//
//

public class Utwor implements Dzwiek {
	private String tytul;
	private float czas;

	public Utwor(String tytul, float czas) {
		this.tytul = tytul;
		this.czas = czas;
	}
	public void start() {
		System.out.println("Odtwarzam utwór: " + tytul + "Czas: " + czas);
	}

	@Override
	public void stop() {
		System.out.println("Zatrzymaj utwór: " + tytul);
	}
}
