package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Biblioteka.java
//  @ Date : 31.05.2025
//  @ Author : 
//
//


import java.util.ArrayList;
import java.util.List;

public class Biblioteka implements StworzIterator {
	private List<Ksiazka> ksiazki = new ArrayList<>();

	public void dodajKsiazke(Ksiazka k) {
		ksiazki.add(k);
	}

	@Override
	public iterator stworzIteratorPoTytule(String tytul) {
		return new IteratorPoBibliotece(ksiazki, tytul, false);
	}

	@Override
	public iterator stworzIteratorPoAutorze(String autor) {
		return new IteratorPoBibliotece(ksiazki, autor, true);
	}
}
