package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : iterator.java
//  @ Date : 31.05.2025
//  @ Author : 
//
//

public interface iterator {
	public Ksiazka nastepny();
	public boolean czyDostepnyNastepny();
}
