package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IteratorPoBibliotece.java
//  @ Date : 31.05.2025
//  @ Author : 
//
//


import java.util.List;

public class IteratorPoBibliotece implements iterator {
	private List<Ksiazka> ksiazki;
	private String filtr;
	private boolean filtrujPoAutorze;
	private int indeks = 0;

	public IteratorPoBibliotece(List<Ksiazka> ksiazki, String filtr, boolean filtrujPoAutorze) {
		this.ksiazki = ksiazki;
		this.filtr = filtr;
		this.filtrujPoAutorze = filtrujPoAutorze;
		przeskoczNiepasujace();
	}

	@Override
	public boolean czyDostepnyNastepny() {
		return indeks < ksiazki.size();
	}

	@Override
	public Ksiazka nastepny() {
		Ksiazka k = ksiazki.get(indeks++);
		przeskoczNiepasujace();
		return k;
	}

	private void przeskoczNiepasujace() {
		while (indeks < ksiazki.size()) {
			Ksiazka k = ksiazki.get(indeks);
			boolean pasuje = filtrujPoAutorze ? k.getAutor().equals(filtr) : k.getTytul().equals(filtr);
			if (pasuje) break;
			indeks++;
		}
	}
}
