package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : KuchniaWLoska.java
//  @ Date : 28.05.2025
//  @ Author : 
//
//

class WloskaPrzystawka implements Przystawka {
	public void podaj() {
		System.out.println("Makaron");
	}
}

class WloskaDanieGlowne implements DanieGLowne {
	public void podaj() {
		System.out.println("Pizza");
	}
}

class WloskaDeser implements Deser {
	public void podaj() {
		System.out.println("Tiramisu");
	}
}


public class KuchniaWLoska implements Kuchnia {
	public Przystawka utworzPrzystawke() {
		return new WloskaPrzystawka();
	}

	public DanieGLowne utworzDanieGlowne() {
		return new WloskaDanieGlowne();
	}

	public Deser utworzDeser() {
		return new WloskaDeser();
	}
}
