package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StworzIterator.java
//  @ Date : 31.05.2025
//  @ Author : 
//
//

public interface StworzIterator {
	iterator stworzIteratorPoTytule(String tytul);
	iterator stworzIteratorPoAutorze(String autor);
}
