package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : uzytkownik.java
//  @ Date : 31.05.2025
//  @ Author : 
//
//




public class uzytkownik {
    private Biblioteka biblioteka;

    public uzytkownik(Biblioteka biblioteka) {
        this.biblioteka = biblioteka;
    }

    public void wyszukajIPokazPoAutorze(String autor) {
        iterator iterator = biblioteka.stworzIteratorPoAutorze(autor);
        while (iterator.czyDostepnyNastepny()) {
            System.out.println(iterator.nastepny());
        }
    }

    public void wyszukajIPokazPoTytule(String tytul) {
        iterator iterator = biblioteka.stworzIteratorPoTytule(tytul);
        while (iterator.czyDostepnyNastepny()) {
            System.out.println(iterator.nastepny());
        }
    }
}
