package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DietaStrategia.java
//  @ Date : 09.06.2025
//  @ Author : 
//
//

public interface DietaStrategia {
	String zaplanujPosilek();
	int dziennyLimitKalorii();
}
