package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ketogeniczna.java
//  @ Date : 09.06.2025
//  @ Author : 
//
//

public class Ketogeniczna implements DietaStrategia {
	@Override
	public String zaplanujPosilek() {
		return "Stek, warzywa, jajka";
	}

	@Override
	public int dziennyLimitKalorii() {
		return 2400;
	}
}
