package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Osoba.java
//  @ Date : 09.06.2025
//  @ Author : 
//
//

public class Osoba {
	private String imie;
	private int wiek;
	private double aktywnoscFizyczna;
	private DietaStrategia strategiaDiety;

	public Osoba(String imie, int wiek, double aktywnoscFizyczna, DietaStrategia strategiaDiety) {
		this.imie = imie;
		this.wiek = wiek;
		this.aktywnoscFizyczna = aktywnoscFizyczna;
		this.strategiaDiety = strategiaDiety;
	}

	public void jedz() {
		System.out.println(imie + " je: " + strategiaDiety.zaplanujPosilek());
	}

	public void zmienStrategie(DietaStrategia nowaStrategia) {
		this.strategiaDiety = nowaStrategia;
		System.out.println(imie + " zmienia dietę.");
	}

	public int zapotrzebowanieKaloryczne() {
		int bazoweKalorie = 2200;
		return (int) (bazoweKalorie * aktywnoscFizyczna);
	}

	public void pokazInfo() {
		System.out.println("Imię: " + imie);
		System.out.println("Zapotrzebowanie kaloryczne: " + zapotrzebowanieKaloryczne() + " kcal");
		System.out.println("Limit z diety: " + strategiaDiety.dziennyLimitKalorii() + " kcal");
	}
}
