package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Weganska.java
//  @ Date : 09.06.2025
//  @ Author : 
//
//

public class Weganska implements DietaStrategia {

	@Override
	public String zaplanujPosilek() {
		return "Sałatka z tofu, ryz, warzywa grillowane";
	}

	@Override
	public int dziennyLimitKalorii() {
		return 2400;
	}
}
