package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Wegetarianska.java
//  @ Date : 09.06.2025
//  @ Author : 
//
//

public class Wegetarianska implements DietaStrategia {
	@Override
	public String zaplanujPosilek() {
		return "Grillowana ryba, sałatka z pomidorów i oliwy";
	}

	@Override
	public int dziennyLimitKalorii() {
		return 2400;
	}
}
