package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CentrumPowiadomien.java
//  @ Date : 14.06.2025
//  @ Author : 
//
//


import java.util.HashMap;
import java.util.Map;

public class CentrumPowiadomien {
	private final Map<String, PowiadomieniaStyl> style = new HashMap<>();

	public PowiadomieniaStyl pobierzStyl(String kolor, String ikonka) {
		String klucz = kolor + "_" + ikonka;
		if (!style.containsKey(klucz)) {
			style.put(klucz, new PowiadomieniaStyl(kolor, ikonka));
		}
		return style.get(klucz);
	}
}
