package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PowiadomieniaStyl.java
//  @ Date : 14.06.2025
//  @ Author : 
//
//

public class PowiadomieniaStyl {
	private String kolor;
	private String ikonka;

	public PowiadomieniaStyl(String kolor, String ikonka) {
		this.kolor = kolor;
		this.ikonka = ikonka;
	}

	public void rysuj(int x, int y, String wiadomosc) {
		System.out.printf(" %s  %s  (%d,%d): %s%n", ikonka, kolor, x, y, wiadomosc);
	}
}
