package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TablicaPowiadomien.java
//  @ Date : 14.06.2025
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.List;

public class TablicaPowiadomien {
	private final List<Powiadomienie> powiadomienia = new ArrayList<>();

	public void dodajPowiadomienie(int x, int y, String wiadomosc, PowiadomieniaStyl styl) {
		powiadomienia.add(new Powiadomienie(x, y, wiadomosc, styl));
	}

	public void pokazPowiadomienia() {
		for (Powiadomienie p : powiadomienia) {
			p.rysuj();
		}
	}
}
