package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Autoryzacja.java
//  @ Date : 22.05.2025
//  @ Author : 
//
//


public class Autoryzacja {
	private boolean zalogowany = false;

	public void zaloguj(String login, String haslo) {
		zalogowany = true;
		System.out.println("Zalogowano" +login);
	}
	
	public void wyloguj() {
		zalogowany = false;
		System.out.println("Wylogowano");
	}

	public boolean czyZalogowany() {
		return zalogowany;
	}
}
