package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : KuchniaPolska.java
//  @ Date : 28.05.2025
//  @ Author : 
//
//

class PolskaPrzystawka implements Przystawka {
	public void podaj() {
		System.out.println("Pierogi");
	}
}

class PolskaDanieGlowne implements DanieGLowne {
	public void podaj() {
		System.out.println("Schabowy z ziemniakami");
	}
}

class PolskaDeser implements Deser {
	public void podaj() {
		System.out.println("Sernik");
	}
}

public class KuchniaPolska implements Kuchnia {
	public Przystawka utworzPrzystawke() {
		return new PolskaPrzystawka();
	}

	public DanieGLowne utworzDanieGlowne() {
		return new PolskaDanieGlowne();
	}

	public Deser utworzDeser() {
		return new PolskaDeser();
	}
}
