package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Platnosci.java
//  @ Date : 22.05.2025
//  @ Author : 
//
//


public class Platnosci {
	public void zaplac(double kwota) {
		System.out.println(kwota + " zl");
	}
	
	public void zwroc(double kwota) {
		System.out.println(kwota + " zl");
	}
}
