package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StanProduktu.java
//  @ Date : 22.05.2025
//  @ Author : 
//
//




public class StanProduktu {

	public boolean dostepnoscProduktu(Produkt produkt) {
		System.out.println("Dostepnosc  " + produkt.getOpis());
		return true;
	}
}
