package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.java
//  @ Date : 22.05.2025
//  @ Author : 
//
//




public class Uzytkownik {
}
