package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Zam�wienie.java
//  @ Date : 22.05.2025
//  @ Author : 
//
//
import java.util.ArrayList;
import java.util.List;

public class Zamowienie {


		private List<Produkt> produkty = new ArrayList<>();

		public void dodajProdukt(Produkt produkt) {
			produkty.add(produkt);
			System.out.println("Dodano produkt do zamówienia:  " + produkt.getOpis());
		}

		public void usunProdukt() {
			if (!produkty.isEmpty()) {
				Produkt p = produkty.remove(produkty.size() - 1);
				System.out.println("Usunięto produkt: " + p.getOpis());
			} else {
				System.out.println("Zamówienie jest puste.");
			}
		}

		public double obliczSume() {
			return produkty.stream().mapToDouble(Produkt::getCena).sum();
		}

}
