package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PlatnoscKarta.java
//  @ Date : 01.06.2025
//  @ Author : 
//
//

public class PlatnoscKarta implements Platnosc {
	private String numerKarty;
	private float stan;

	public PlatnoscKarta(String numerKarty, float stan) {
		this.numerKarty = numerKarty;
		this.stan = stan;
	}

	public float getStan() {
		return stan;
	}

	public String getNumerKarty() {
		return numerKarty;
	}

	@Override
	public void anulluj() {
		System.out.println("Platnosc anulowana");
	}

	@Override
	public void zaplac(float kwota) {
		if (kwota <= stan) {
			stan -= kwota;
			System.out.println("Zapłacono kartą: " + kwota + " zł");
		} else {
			System.out.println("Brak środków na karcie.");
		}
	}
}
