package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Platnosc.java
//  @ Date : 01.06.2025
//  @ Author : 
//
//

public interface Platnosc {
	public void anulluj();
	public void zaplac(float kwota);
}
