package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SerwerPlatnosci.java
//  @ Date : 01.06.2025
//  @ Author : 
//
//

public class SerwerPlatnosci implements Platnosc {
	private Platnosc realnaPlatnosc;

	public SerwerPlatnosci(Platnosc realnaPlatnosc) {
		this.realnaPlatnosc = realnaPlatnosc;
	}

	private void usunPlatnosc() {
		System.out.println("Platnosc usunieta");
	}
	
	public void dodajPlatnosc() {
		System.out.println("Dodano platnosc do serwera");
	}

	@Override
	public void anulluj() {
		System.out.println("Anulowania płatności");
		realnaPlatnosc.anulluj();
	}

	@Override
	public void zaplac(float kwota) {
		System.out.println("Przetwarzanie płatności");
		realnaPlatnosc.zaplac(kwota);
	}
}
