package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.java
//  @ Date : 01.06.2025
//  @ Author : 
//
//

public class Uzytkownik {
    private Platnosc platnosc;

    public Uzytkownik(Platnosc platnosc) {
        this.platnosc = platnosc;
    }

    public void wykonajPlatnosc(float kwota) {
        System.out.println("Użytkownik wykonuje płatność...");
        platnosc.zaplac(kwota);
    }

    public void anulujPlatnosc() {
        System.out.println("Użytkownik anuluje płatność...");
        platnosc.anulluj();
    }
}
