package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SprawdzBiometrie.java
//  @ Date : 10.06.2025
//  @ Author : 
//
//


public class SprawdzBiometrie extends Sprawdz {
	@Override
	public void obsluz(Uzytkownik uzytkownik) {
		System.out.println("Sprawdzam biometrię...");
		if ("odcisk123".equals(uzytkownik.odciskPalca)) {
			System.out.println("Uwierzytelniono przez biometrie.");
		} else {
			System.out.println("Błędna biometryka.");
			przekazDalej(uzytkownik);
		}
	}
}
