package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SprawdzPIN.java
//  @ Date : 10.06.2025
//  @ Author : 
//
//

public class SprawdzPIN extends Sprawdz {
	@Override
	public void obsluz(Uzytkownik uzytkownik) {
		System.out.println("Sprawdzam PIN.");
		if ("1234".equals(uzytkownik.pin)) {
			System.out.println("Uwierzytelniono przez PIN.");
		} else {
			System.out.println("Błędny PIN.");
			przekazDalej(uzytkownik);
		}
	}
}
