package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sprawdz.java
//  @ Date : 10.06.2025
//  @ Author : 
//
//

public abstract class Sprawdz implements WeryfikacjaTozsamosci {
	protected WeryfikacjaTozsamosci nastepny;

	@Override
	public WeryfikacjaTozsamosci ustawNastepny(WeryfikacjaTozsamosci nastepny) {
		this.nastepny = nastepny;
		return nastepny;
	}


	protected void przekazDalej(Uzytkownik uzytkownik) {
		if (nastepny != null) {
			nastepny.obsluz(uzytkownik);
		} else {
			System.out.println(" Żaden etap weryfikacji się nie powiódł.");
		}
	}
}
