package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WeryfikacjaTozsamosci.java
//  @ Date : 10.06.2025
//  @ Author : 
//
//

public interface WeryfikacjaTozsamosci {
	WeryfikacjaTozsamosci ustawNastepny(WeryfikacjaTozsamosci nastepny);
	
	public void obsluz(Uzytkownik uzytkownik);
}
