package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Weryfikacja.java
//  @ Date : 10.06.2025
//  @ Author : 
//
//

public class Weryfikacja  {
	private WeryfikacjaTozsamosci lancuch;

	public Weryfikacja() {
		WeryfikacjaTozsamosci pin = new SprawdzPIN();
		WeryfikacjaTozsamosci haslo = new SprawdzHaslo();
		WeryfikacjaTozsamosci sms = new SprawdzSms();
		WeryfikacjaTozsamosci biometria = new SprawdzBiometrie();

		pin.ustawNastepny(haslo).ustawNastepny(sms).ustawNastepny(biometria);
		this.lancuch = pin;
	}

	public void rozpocznijWeryfikacje(Uzytkownik uzytkownik) {
		System.out.println("Weryfikacja dla: " + uzytkownik.imie + " " + uzytkownik.nazwisko);
		lancuch.obsluz(uzytkownik);
	}
}
