package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Anglik.java
//  @ Date : 02.06.2025
//  @ Author : 
//
//

public class Anglik {
	public void rozmawaPoAngielsku() {
		System.out.println("I speak English!");
	}
}
