package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : InnyJezyk.java
//  @ Date : 02.06.2025
//  @ Author : 
//
//

public interface InnyJezyk {
	 void rozmawiajPoAngielsku();
}
