package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Kucharz.java
//  @ Date : 28.05.2025
//  @ Author : 
//
//

public class Kucharz {
	private Kuchnia kuchnia;

	public Kucharz(Kuchnia kuchnia) {
		this.kuchnia = kuchnia;
	}

	public void przygotujZestaw() {
		Przystawka przystawka = kuchnia.utworzPrzystawke();
		DanieGLowne danieGlowne = kuchnia.utworzDanieGlowne();
		Deser deser = kuchnia.utworzDeser();

		przystawka.podaj();
		danieGlowne.podaj();
		deser.podaj();
	}
}
