package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Polak.java
//  @ Date : 02.06.2025
//  @ Author : 
//
//

public class Polak {
	private InnyJezyk rozmowca;

	public Polak(InnyJezyk rozmowca) {
		this.rozmowca = rozmowca;
	}

	public void rozmawiaj() {
		System.out.println("Chcialbym z kimś porozmaiwać po angielsku");
		rozmowca.rozmawiajPoAngielsku();
	}
}
