package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tlumacz.java
//  @ Date : 02.06.2025
//  @ Author : 
//
//

public class Tlumacz implements InnyJezyk {
	private Anglik anglik;


	public Tlumacz(Anglik anglik) {
		this.anglik = anglik;
	}

	@Override
	public void rozmawiajPoAngielsku() {
		System.out.println("Tlumacz: Translating...");
		anglik.rozmawaPoAngielsku();
	}
}
