package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GraKarciana.java
//  @ Date : 11.06.2025
//  @ Author : 
//
//

public abstract class GraKarciana {
	public void rozegrajGre() {
		potasujTalie();
		rozdajKarty();
		fazaLicytacji();
		rozgrywka();
		punktacja();
		zwyciezca();
	}
	
	public void potasujTalie() {
		System.out.println("Tasuje talie.");
	}
	
	public abstract void rozdajKarty();
	
	public abstract void  fazaLicytacji();
	
	public abstract void rozgrywka();
	
	public abstract void punktacja();
	
	public abstract void zwyciezca();

}
