package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GraPan.java
//  @ Date : 11.06.2025
//  @ Author : 
//
//


public class GraPan extends GraKarciana {

	@Override
	public void rozdajKarty() {
		System.out.println("Rozdaje po 5 kart kazdemu");
	}

	@Override
	public void rozgrywka() {
		System.out.println("Gracze zagrywaja pasujace karty");
	}

	@Override
	public void zwyciezca() {
		System.out.println("Wygrywa osoba, która pozbyła się kart");
	}

	public void punktacja() {
		System.out.println("Liczba kart");
	}

	@Override
	public void fazaLicytacji() {

	}
}
