package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GraPiatka.java
//  @ Date : 11.06.2025
//  @ Author : 
//
//

public class GraPiatka extends GraKarciana {

	@Override
	public void rozdajKarty() {
		System.out.println("Rozdaje po 5 kart kazdemu z graczy");
	}

	@Override
	public void fazaLicytacji() {
		System.out.println("Mozliwa wymiana kart");
	}

	@Override
	public void rozgrywka() {
		System.out.println("Rozgywka");
	}

	@Override
	public void punktacja() {
		System.out.println("Porownanie kart");
	}

	@Override
	public void zwyciezca() {
		System.out.println("Wygrywa osoba z najlepszym ukladem kart");
	}

}
