package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GraTysiac.java
//  @ Date : 11.06.2025
//  @ Author : 
//
//

public class GraTysiac extends GraKarciana {

	@Override
	public void rozdajKarty() {
		System.out.println("Rozdaje karty: jenda osoba 3 karty, reszta 7 kart");
	}

	@Override
	public void fazaLicytacji() {
		System.out.println("Licytacja");
	}

	@Override
	public void rozgrywka() {
		System.out.println("Rozgrywka");
	}

	@Override
	public void punktacja() {
		System.out.println("Podliczneie punktów z meldunków i lew");
	}

	@Override
	public void zwyciezca() {
		System.out.println("Zwycieza gracz z mimimum 1000pkt");
	}
}
