package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OdtwarzaczMuzyki.java
//  @ Date : 12.06.2025
//  @ Author : 
//
//

public class OdtwarzaczMuzyki {
	private Stan stan;

	public OdtwarzaczMuzyki() {
		this.stan = new StanGotowy(this);
	}

	public void zmienStan(Stan nowyStan) {
		this.stan = nowyStan;
	}

	public void odtworz() {
		System.out.println("Odtwarzanie.");
	}

	public void nastepny() {
		System.out.println("Następny utwór.");
	}

	public void poprzedni() {
		System.out.println("Poprzedni utwór.");
	}

	public void zatrzymaj() {
		System.out.println("Zatrzymywanie.");
	}

	public void kliknijOtworzZatrzymaj() {
		stan.KliknijOtworzZatrzymaj();
	}

	public void kliknijPoprzedni() {
		stan.kliknijPoprzedni();
	}

	public void kliknijNastepny() {
		stan.kliknijNastepny();
	}
}
