package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StanOdtwarza.java
//  @ Date : 12.06.2025
//  @ Author : 
//
//

public class StanOdtwarza extends Stan {
	public StanOdtwarza(OdtwarzaczMuzyki odtwarzacz) {
		super(odtwarzacz);
	}
	@Override
	public void KliknijOtworzZatrzymaj() {
		odtwarzacz.zatrzymaj();
		odtwarzacz.zmienStan(new StanWstrzymany(odtwarzacz));
	}

	@Override
	public void kliknijPoprzedni() {
		odtwarzacz.poprzedni();
	}

	@Override
	public void kliknijNastepny() {
		odtwarzacz.nastepny();
	}
}
