package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StanWstrzymany.java
//  @ Date : 12.06.2025
//  @ Author : 
//
//

public class StanWstrzymany extends Stan {
	public StanWstrzymany(OdtwarzaczMuzyki odtwarzacz) {
		super(odtwarzacz);
	}

	@Override
	public void KliknijOtworzZatrzymaj() {
		odtwarzacz.odtworz();
		odtwarzacz.zmienStan(new StanOdtwarza(odtwarzacz));
	}

	@Override
	public void kliknijPoprzedni() {
		odtwarzacz.poprzedni();
	}

	@Override
	public void kliknijNastepny() {
		odtwarzacz.nastepny();
	}
}
