package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Stan.java
//  @ Date : 12.06.2025
//  @ Author : 
//
//

abstract class Stan {
	protected OdtwarzaczMuzyki odtwarzacz;

	public Stan(OdtwarzaczMuzyki odtwarzacz) {
		this.odtwarzacz = odtwarzacz;
	}
	
	public abstract void KliknijOtworzZatrzymaj();
	
	public abstract void kliknijPoprzedni();
	
	public abstract void kliknijNastepny();
}
