package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StanGotowy.java
//  @ Date : 12.06.2025
//  @ Author : 
//
//

public class StanGotowy extends Stan {
	public StanGotowy(OdtwarzaczMuzyki odtwarzacz) {
		super(odtwarzacz);
	}

	@Override
	public void KliknijOtworzZatrzymaj() {
		odtwarzacz.odtworz();
		odtwarzacz.zmienStan(new StanOdtwarza(odtwarzacz));
	}

	@Override
	public void kliknijPoprzedni() {
		System.out.println("Brak utworu do cofnięcia.");
	}

	@Override
	public void kliknijNastepny() {
		System.out.println("Brak utworu do przeskoczenia.");
	}
}
