package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MediatorPowiadomien.java
//  @ Date : 05.06.2025
//  @ Author : 
//
//

public class MediatorPowiadomien implements Mediator {
	public PowiadomienieEmail powiadomienieEmail;
	public PowiadomienieSms powiadomienieSms;
	public PowiadomieniePocztaGlosowa powiadomieniePocztaGlosowa;
	public Uzytkownik uzytkownik;

	@Override
	public void notify(Object nadawca, String opcja) {
		if (nadawca == uzytkownik && opcja.equals("akcjaUzytkownika")) {
			powiadomienieEmail.wyslijEmail();
			powiadomienieSms.wyslijSms();
			powiadomieniePocztaGlosowa.wyslijPoczteGlosowa();
		}
	}
}
