package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mediator.java
//  @ Date : 05.06.2025
//  @ Author : 
//
//

public interface Mediator {
	public void notify(Object nadawca, String opcja);
}
