package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PowiadomieniePocztaGlosowa.java
//  @ Date : 05.06.2025
//  @ Author : 
//
//


public class PowiadomieniePocztaGlosowa extends Powiadomenia{

	public PowiadomieniePocztaGlosowa(Mediator mediator) {
		super(mediator);
	}

	public void wyslijPoczteGlosowa() {
		System.out.println("Wyslano wiadomosc glosowa");
	}
}
