package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PowiadomienieSms.java
//  @ Date : 05.06.2025
//  @ Author : 
//
//

public class PowiadomienieSms extends Powiadomenia{

	public PowiadomienieSms(Mediator mediator) {
		super(mediator);
	}

	public void wyslijSms() {
		System.out.println("Wyslano SMS");
	}
}
