package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PowiadomienieEmail.java
//  @ Date : 05.06.2025
//  @ Author : 
//
//


public class PowiadomienieEmail extends Powiadomenia {

	public PowiadomienieEmail(Mediator mediator) {
		super(mediator);
	}

	public void wyslijEmail() {
		System.out.println("Wyslano Email");
	}
}
