package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Powiadomenia.java
//  @ Date : 05.06.2025
//  @ Author : 
//
//

public abstract class Powiadomenia {
	protected Mediator mediator;

	public Powiadomenia(Mediator mediator) {
		this.mediator = mediator;
	}
}
