package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.java
//  @ Date : 05.06.2025
//  @ Author : 
//
//


public class Uzytkownik {
	private Mediator mediator;

	public Uzytkownik(Mediator mediator) {
		this.mediator = mediator;
	}

	public void wykonaj() {
		System.out.println(" Użytkownik wykonuje akcję");
		mediator.notify(this, "akcjaUzytkownika");
	}
}
