package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Kuchnia.java
//  @ Date : 28.05.2025
//  @ Author : 
//
//

public interface   Kuchnia {
	Przystawka utworzPrzystawke();
	DanieGLowne utworzDanieGlowne();
	Deser utworzDeser();
}
