package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LogowanieZwykle.java
//  @ Date : 27.05.2025
//  @ Author : 
//
//

public class LogowanieZwykle implements Logowanie {
	public void zaloguj() {
		System.out.println("Zalogowano uzytkownika ");
	}
}
