package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Logowanie.java
//  @ Date : 27.05.2025
//  @ Author : 
//
//

public interface Logowanie {
	void zaloguj();
}
