package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LogowaniePremium.java
//  @ Date : 27.05.2025
//  @ Author : 
//
//


public class LogowaniePremium extends LogowanieDekorator {
	public LogowaniePremium(Logowanie logowanie) {
		super(logowanie);
	}

	@Override
	public void zaloguj() {
		super.zaloguj();
		sms();
	}

	public void sms() {
		System.out.println("Kod do aktywacji: asdfges");
	}
}
