package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LogowanieDekorator.java
//  @ Date : 27.05.2025
//  @ Author : 
//
//

public abstract class LogowanieDekorator implements Logowanie {
	private Logowanie logowanie;

	public LogowanieDekorator(Logowanie logowanie) {
		this.logowanie = logowanie;
	}

	@Override
	public void zaloguj() {
		logowanie.zaloguj();
	}
}
