package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LogowanieZLogiem.java
//  @ Date : 27.05.2025
//  @ Author : 
//
//




public class LogowanieZLogiem extends LogowanieDekorator {
	public LogowanieZLogiem(Logowanie logowanie) {
		super(logowanie);
	}

	@Override
	public void zaloguj() {
		super.zaloguj();
		System.out.println("Zalogowano uzytkownika, zapisano log ");
	}
}
