package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LogowanieZOgraniczeniami.java
//  @ Date : 27.05.2025
//  @ Author : 
//
//

public class LogowanieZOgraniczeniami extends LogowanieDekorator {

	private int wiek;
	public LogowanieZOgraniczeniami(Logowanie logowanie, int wiek) {
		super(logowanie);
		this.wiek = wiek;
	}

	@Override
	public void zaloguj() {
		if(wiek > 17){
			super.zaloguj();
			System.out.println("Spelnia wymagania ");
		} else {
			System.out.println("Uzytkownik jest niepelnoletni, logowanie zablokowane");
		}
	}
}
