package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.java
//  @ Date : 27.05.2025
//  @ Author : 
//
//

public class Uzytkownik {
    private Logowanie logowanie;
    private int wiek;

    public Uzytkownik(Logowanie logowanie, int wiek) {
        this.logowanie = logowanie;
        this.wiek = wiek;
    }

    public void loguj(){
        logowanie.zaloguj();
    }

    public int getWiek() {
        return wiek;
    }

    public void setWiek(Logowanie logowanie) {
        this.logowanie = logowanie;
    }

}
